config/routes.rb
DicomManager::Application.routes.draw do

	 resources :messages, :only => [:new, :create] do
     post 'act_admission_request', on: :member
	   collection do
       get 'admission_request'
       post 'send_admission_request'
	     get 'token' => 'messages#token', :as => 'token'
	     post 'empty/:messagebox' => 'messages#empty', :as => 'empty'
	     put 'update' => 'messages#update'
	     get ':messagebox/show/:id' => 'messages#show', :as => 'show', :constraints => { :messagebox => /inbox|outbox|trash/ }
	     get '(/:messagebox)' => 'messages#index', :as => 'box', :constraints => { :messagebox => /inbox|outbox|trash/ }
	   end
	 end


  devise_for :users, controllers: { registrations: "users/registrations" }

  namespace :admin do
    resources :users, constraints: { id: /[^\/]+/ }
    resources :groups, only: [:index]
    resources :projects, only: [:index]
    resources :catalogs, only: [:index]
  end

  namespace :user do
    resources :groups
    resources :projects
  end

  #resources
  resources :permissions
  resources :groups
  resources :projects
  resources :users do
    member do
      get 'edit_share'
      post 'update_share'
    end
  end
  resources :catalogs do
    post 'move', on: :member
    resources :dicom_files do
      post 'manage', on: :collection
      get 'view', on: :member
    end
  end


  #paths
  root :to => "static_pages#home"

  match '/help', to: "static_pages#help"

  match '/about', to: "static_pages#about"
end

app/models/message.rb
class Message < ActiveRecord::Base

  has_ancestry

  belongs_to :user, :class_name => "User"
  belongs_to :sender, class_name: "User", foreign_key: 'sender_id', validate: true

  attr_accessible :user_id,
                  :sender_id,
                  :recipient_id,
                  :subject_id,
                  :subject,
                  :content,
                  :opened,
                  :deleted,
                  :copies,
                  :parent_id,
                  :request

  validates_presence_of :user_id, :sender_id, :recipient_id, :subject_id, :subject

  def self.sequence_subject_id
    id = self.maximum(:subject_id).to_i
    id = 0 if id.nil?
    id += 1
    id
  end

  def self.next_parent_id(parent_id)
    parent_id = parent_id.to_i - 1
    if self.where(:id => parent_id).empty?
      parent_id = nil
    end
    parent_id
  end

  def is_request?
    self.request.present?
  end

  def read?
    self.opened?
  end

  def mark_as_read
    self.update_attributes!(:opened => true) 
  end

  def mark_as_unread
    self.update_attributes!(:opened => false)
  end

  def delete
    unless self.deleted?
      self.update_attributes!(:deleted => true) 
    else
      self.destroy
    end
  end

  def undelete
    self.update_attributes!(:deleted => false)
  end

  def from
    User.find_by_id(self.sender_id)
  end

  def to
    User.find_by_id(self.recipient_id)
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :authenticate_user!
  def index
    @messagebox = params[:messagebox].blank? ? "inbox" : params[:messagebox]
    @messages = current_user.send(@messagebox).group(:subject_id).page(params[:page]).per(10)

    case @messagebox
    when "trash"
      @options = ["Read","Unread","Delete","Undelete"]
    else
      @options = ["Read","Unread","Delete"]
    end
  end
	
	def show
    unless params[:messagebox].blank?
      message = current_user.send(params[:messagebox]).find(params[:id])

      @messages = message.root.subtree
      @parent_id = @messages.last.id

      if @messages.last.copies
        @user_tokens = @messages.last.recipient_id
        @parent_id = @messages.last.ancestor_ids.last unless @parent_id.nil?
      else
        @user_tokens = @messages.last.sender_id
      end

      read_unread_messages(true, *@messages)
    end
	end

  def admission_request
    @new_groups = Group.where('id NOT IN (?)', (current_user.groups + current_user.created_groups).uniq)
  end

  def send_admission_request
    if params[:admission_request][:project_id].present?
      recipient = Project.find(params[:admission_request][:project_id])
      group = Group.find(params[:admission_request][:group_id])
      request = "G:#{group.id}:#{recipient.id}"
      subject = "### #{group.name} (Group) join request for '#{recipient.name}' (Project) ###"
    elsif params[:admission_request][:group_id].present?
      recipient = Group.find(params[:admission_request][:group_id])
      request = "U:#{current_user.id}:#{recipient.id}"
      subject = "### #{current_user.full_name} (User) join request for '#{recipient.name}' (Group) ###"
    else
      flash[:error] = "Can not send empty request"
      redirect_to :back
    end

    if current_user.send_message?(recipients: [recipient.author], subject_id: nil, subject: subject, content: '', parent_id: nil, request: request )
      flash[:success] = "Successfully send join request."
    else
      flash[:error] = "Could not send the request."
    end
    redirect_to root_path
  end

  def act_admission_request
    req = Message.find(params[:id])
    req_params = req.request.split(':')

    case req_params[0]
    when "U"
      req_author = User.find(req_params[1])
      req_target = Group.find(req_params[2])
      resource = " "
    else
      req_author = Group.find(req_params[1])
      req_target = Project.find(req_params[2])
      resource = " '#{req_author.name}' (#{req_author.class.to_s}) "
    end

    if params[:decision] == 'accept'
      past_tense = "ed"

      case req_params[0]
      when "U"
        req_author.groups << req_target
      else
        past_tense = "d"
        req_author.projects << req_target
      end
    else
      past_tense = "d"
    end

    subject = "#{params[:decision].titleize + past_tense} your request for joining" + resource + "to '#{req_target.name}' (#{req_target.class.to_s})"
    p subject
    current_user.send_message?(recipients: [req.sender], subject_id: nil, subject: subject, content: subject, parent_id: nil)
    req.update_column(:opened, true)

    redirect_to messages_path(:inbox)
  end

	def new
	end

	def create
    unless params[:user_tokens].blank? or params[:subject].blank? or params[:content].blank?
      recipients = User.find(params[:user_tokens].split(",").collect { |id| id.to_i })
      if current_user.send_message?(:recipients => recipients, :subject_id => params[:subject_id], :subject => params[:subject], :content => params[:content], :parent_id => params[:parent_id])
        redirect_to box_messages_url(:inbox), :notice => 'Successfully send message.'
      else
        flash.now[:alert] = "Unable to send message."
        render "new"
      end
    else
      flash.now[:alert] = "Invalid input for sending message."
      render "new"
    end
	end

	def update
    unless params[:messages].nil?
      _message = current_user.send(params[:messagebox]).find(params[:messages])
      _message.each do |message|
        messages = message.root.subtree
        if params[:option].downcase == "read"
          read_unread_messages(true,*messages)
        elsif params[:option].downcase == "unread"
          read_unread_messages(false,*messages)
        elsif params[:option].downcase == "delete"
          delete_messages(true,*messages)
        elsif params[:option].downcase == "undelete"
          delete_messages(false,*messages)
        end
      end
    end
    redirect_to box_messages_url(params[:messagebox]) 
	end

	def empty
    unless params[:messagebox].nil?
      current_user.empty_messages(params[:messagebox].to_sym => true)
      redirect_to box_messages_url(params[:messagebox]), :notice => "Successfully delete all messages."
    end
	end

	def token
    query = "%" + params[:q] + "%"
    recipients = User.select("id,email").where("email like ?", query)
    respond_to do |format|
      format.json { render :json => recipients.map { |u| { "id" => u.id, "name" => u.email} } }
    end
	end

private

  def read_unread_messages(isRead, *messages)
    messages.each do |msg|
      unless msg.copies
        if isRead
          msg.mark_as_read unless msg.read?
        else
          msg.mark_as_unread if msg.read?
        end
      end
    end
  end

	def delete_messages(isDelete, *messages)
    messages.each do |msg|
      if isDelete
        msg.delete
      else
        msg.undelete
      end
    end
	end

end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_act_request.haml
.request{ "data-message" => message.id, "data-path" => act_admission_request_message_path(message), style: "display: inline;" }
  .btn.btn-mini.btn-primary.accept{ "data-decision" => "accept" }
    Accept
  .btn.btn-mini.btn-danger.decline{ "data-decision" => "decline" }
    Decline

app/views/messages/_head.html.erb
<% content_for :head do %>
	
	<%= stylesheet_link_tag "messages" %>
    <%= javascript_include_tag "messages" %>
	
    <%- if controller.action_name == "new" -%>
    <%= stylesheet_link_tag "token-input-facebook" %>
    <%= javascript_include_tag "jquery.tokeninput" %>
    <script type="text/javascript">
	
		$(document).ready(function() {
			$("#user_tokens").tokenInput("/messages/token.json", {
			    crossDomain: false,
			    theme: "facebook"
			});
		});
		
	</script>
    <%- end -%>
<% end %>

app/views/messages/_messages.html.erb
<%= form_tag messages_path, :method => :put, :remote => true do %>
<table class="pretty" width="100%">
	 <tbody>
		<tr>
			<td class="middle">
				<input type="checkbox" class="checkall" id="checkbox" name="checkbox">
			</td>
			<td colspan="3">
			<%= select_tag "option", options_for_select(@options) %>
			<%= submit_tag "Apply to Selected" %>
			<%= link_to "Empty #{@messagebox}", empty_messages_path(@messagebox), :confirm => "Are you sure want to delete all?", :method => :post %>
			<%= hidden_field_tag :messagebox, @messagebox %>
			</td>
		</tr>
<!-- this will render the messages -->
<%-
		x = 0
		@messages.reverse_each do |message|
			convTree = message.root.subtree
			
			flag = convTree.where(:copies => false).empty?
			display_names = convTree.collect do |c|
				unless flag
					c.copies ? "me" : c.from.full_name
				else
					c.to.full_name
				end
			end.uniq.join(", ").concat( convTree.count > 1 ? " (#{convTree.count})" : "")
			
			style = ""
			flag = convTree.where(:copies => false, :opened => false).empty?
			unless flag
				style = "unread "
			end
			style << "alt" if ((x += 1) % 2 == 0)
			
			title = convTree.last.created_at.strftime("%a, %b %d, %Y at %I:%M %p")
			created_at = convTree.last.created_at.strftime( ((convTree.last.created_at < 1.days.ago) ? "%b %d, %Y" : "%I:%M %p"))
		-%>
		<tr class="<%= style -%>">
			<td><%= check_box_tag "[messages][]", message.id %></td>
        <td><%= display_names %></td>
        <%- if message.is_request? %>
          <td>
            <%= message.subject %>
            <%- unless message.opened? %>
              <%= render partial: "act_request", locals: { message: message } %>
            <%- end %>
          </td>
        <%- else %>
          <td><%= link_to message.subject, show_messages_path(@messagebox, message.id) %></td>
        <%- end %>
		    <td title='<%= title %>'><%= created_at %></td>
		</tr>
		<%- end -%>
<!-- END MESSAGES -->
		<tr>
			<td colspan="4"><%= paginate @messages %></td>
		</tr>
	</tbody>
</table>
<%- end -%>
<p>
	<%= link_to "Compose New Message", new_message_path %>
</p>

app/views/messages/_tabs_panel.html.erb
<ul class="tabs">
    <li class=<%= "active" if @messagebox == "inbox" %>>	
    	<%= link_to "Inbox", box_messages_path(:inbox) %>
    </li>
    <li class=<%= "active" if @messagebox == "outbox" %>>	
    	<%= link_to "Outbox", box_messages_path(:outbox) %>
    </li>
    <li class=<%= "active" if @messagebox == "trash" %>>	
    	<%= link_to "Trash", box_messages_path(:trash) %>
    </li>
</ul>

app/views/messages/admission_request.haml
.row-fluid
  = simple_form_for :admission_request, url: send_admission_request_messages_path, method: :post do |f|
    = f.input :group_id, label: "Choose group you would like to join:", collection: @new_groups, label_method: :name, value_method: :id, include_blank: false
    = f.button :submit, "Send request", class: "btn btn-primary"

app/views/messages/index.html.erb
<h1>Messages</h1>

<%= render "head" %>

<div>
	<%= render "tabs_panel" %>
    <div id="tabs-messages">
		<%= render 'messages' %>
    </div>
</div>

app/views/messages/index.js.erb
$("#tabs-messages").html("<%= escape_javascript(render("messages")) %>");

app/views/messages/new.html.erb
<h1>New Messages</h1>

<%= render "head" %>

<div>
	<%= render :partial => "tabs_panel" %>
    <div id="tabs-messages" style="padding-top:50px;">
		<%= form_tag messages_path, :method => :post do %>
			<p>
			  	<%= label_tag :user_tokens, "User" %><br />
			  	<%= text_field_tag :user_tokens %>
			</p>
			<p>
			    <%= label_tag :subject, "Subject" %><br />
				<%= text_field_tag :subject, nil, :size => 75 %>
			</p>
			<p>
			    <%= label_tag :content, "Messages" %><br />
				<%= text_area_tag :content, nil, :rows => 20, :cols => 55 %>
			</p>
			<p>
				<%= submit_tag "Send" %>
			</p>
		<% end %>
    </div>
</div>

app/views/messages/show.html.erb
<h1>Show Messages</h1>

<%= render "head" %>

<div>
	<%= render :partial => "tabs_panel" %>
	<div id="tabs-messages" style="padding-top:50px;">
		<%= form_tag messages_path, :method => :post do %>
			<h3><%= @messages.last.subject %></h3>
			
			  <% for msg in @messages %>
		    	<div class="message">
				  <div class="created_at"><%= msg.created_at.strftime("%B %d, %Y") %></div>
				  <div class="content">
					<strong><%= msg.from.email %></strong><br />
				    <%= msg.content %>
				  </div>
				</div>
			  <% end %>
			
			<p>
			    <%= label_tag :content, "Reply Message" %><br />
				<%= text_area_tag :content, nil, :rows => 20, :cols => 55 %>
			</p>
			<p>
				<%= submit_tag "Reply" %>
			</p>
			<%= hidden_field_tag :user_tokens, @user_tokens %>
			<%= hidden_field_tag :subject, @messages.last.subject %>
			<%= hidden_field_tag :subject_id, @messages.last.subject_id %>
			<%= hidden_field_tag :parent_id, @parent_id %>
		<% end -%>
    </div>   
</div>