config/routes.rb
DicomManager::Application.routes.draw do

	 resources :messages, :only => [:new, :create] do
     post 'act_admission_request', on: :member
	   collection do
       get 'admission_request'
       post 'send_admission_request'
	     get 'token' => 'messages#token', :as => 'token'
	     post 'empty/:messagebox' => 'messages#empty', :as => 'empty'
	     put 'update' => 'messages#update'
	     get ':messagebox/show/:id' => 'messages#show', :as => 'show', :constraints => { :messagebox => /inbox|outbox|trash/ }
	     get '(/:messagebox)' => 'messages#index', :as => 'box', :constraints => { :messagebox => /inbox|outbox|trash/ }
	   end
	 end


  devise_for :users, controllers: { registrations: "users/registrations" }

  namespace :admin do
    resources :users, constraints: { id: /[^\/]+/ }
    resources :groups, only: [:index]
    resources :projects, only: [:index]
    resources :catalogs, only: [:index]
  end

  namespace :user do
    resources :groups
    resources :projects
  end

  #resources
  resources :permissions
  resources :groups
  resources :projects
  resources :users do
    member do
      get 'edit_share'
      post 'update_share'
    end
  end
  resources :catalogs do
    post 'move', on: :member
    resources :dicom_files do
      post 'manage', on: :collection
      get 'view', on: :member
    end
  end


  #paths
  root :to => "static_pages#home"

  match '/help', to: "static_pages#help"

  match '/about', to: "static_pages#about"
end

app/models/group.rb
# == Schema Information
#
# Table name: groups
#
#  id          :integer(4)      not null, primary key
#  name        :string(255)
#  description :string(255)
#  created_at  :datetime        not null
#  updated_at  :datetime        not null
#  creator_id  :integer(4)
#  updater_id  :integer(4)
#

class Group < ActiveRecord::Base
  include CatalogExtension

  attr_accessible :groups_projects_attributes
  has_many :groups_users, dependent: :destroy
  has_many :users, through: :groups_users
  has_many :groups_projects, dependent: :destroy
  has_many :projects, through: :groups_projects
  has_many :catalogs, as: :catalogable
  has_one :root_catalog, class_name: "Catalog", as: :catalogable, conditions: { ancestry: nil }
  belongs_to :author, class_name: 'User', foreign_key: 'creator_id', validate: true

  accepts_nested_attributes_for :groups_projects

  attr_accessible :name, :description, :catalog_creation, :creator_id, :updater_id
  attr_accessor :assign_current_user

  after_create :create_root_catalog

  def created_by?(user)
    self.creator_id == user.id
  end

  def shares_with_project?(project)
    groups_projects.where(project_id: project).first.share
  end

  def create_root_catalog
    catalog_description = "Root catalog for #{name} (#{self.class.to_s})"
    catalogs.create(name: name.downcase, description: catalog_description)
  end
end

app/controllers/admin/groups_controller.rb
class Admin::GroupsController < ApplicationController
  def index
    @search = Group.search params[:q]
    @groups = @search.result.page params[:page]
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  before_filter :find_group, except: [:index, :create, :new]
  before_filter :assign_user, only: [:create, :update]

  def index
    @search = current_user.groups.search params[:q]
    @groups = @search.result.page params[:page]
  end

  def show
    @new_projects = Project.where("id NOT IN (?)", (current_user.created_projects + @group.projects).uniq)
  end

  def edit
  end

  def new
    @group = Group.new
  end

  def create
    group = @assign_current_user ? current_user.groups.build(params[:group]) : Group.new(params[:group])

    if @assign_current_user ? current_user.save : group.save
      flash[:success] = "Group created"
    else
      flash[:failure] = "Failed to create group"
    end
    redirect_to group_path(group)
  end

  def update
    @assign_current_user ? (current_user.groups << @group unless current_user.groups.include?(@group)) : current_user.groups.delete(@group)

    if current_user.save && @group.update_attributes(params[:group])
      flash[:notice] = "Group updated"
      redirect_to group_path(@group)
    else
      flash[:error] = "Error updating group"
      render :edit
    end
  end

  def find_group
    @group = Group.find params[:id]
  end

  def assign_user
    assign = params[:group].delete(:assign_current_user)
    @assign_current_user = assign == "1" ? true : false
  end
end

app/controllers/user/groups_controller.rb
class User::GroupsController < ApplicationController
  def index
    @search = current_user.created_groups.search params[:q]
    @groups = @search.result.page params[:page]
  end
end

app/views/groups/_form.html.haml
.container-fluid
  = simple_form_for @group, :html => { :class => 'form-horizontal' } do |f|
    .row-fluid
      .span6
        = f.input :name
        = f.input :description
        = f.input :catalog_creation, wrapper_html: { class: 'checkbox' }
        - if @group.new_record? || @group.created_by?(current_user)
          = f.input :assign_current_user, as: :boolean, label: "Assign me to this group", input_html: { checked: (@group.new_record? || current_user.groups.include?(@group)) }, wrapper_html: { class: 'checkbox' }
        = f.button :submit, :class => 'btn-primary'
      .span6
        - if @group.projects.any?
          Share catalogs with projects:
          = f.simple_fields_for :groups_projects do |gp|
            = gp.input :share, label: gp.object.project.name, as: :boolean, wrapper_html: { class: 'checkbox' }

app/views/groups/_request_for_project.haml
.row-fluid
  = simple_form_for :admission_request, url: send_admission_request_messages_path, method: :post, html: { style: "display: inline;" } do |f|
    = f.hidden_field :group_id, value: @group.id
    = f.input :project_id, label: "Choose project you would like to join this group to:", collection: @new_projects, label_method: :name, value_method: :id, include_blank: false
    = f.button :submit, "Send request", class: "btn btn-primary"

app/views/groups/edit.html.haml
- model_class = Group
.page-header
  %h1= "Edit #{model_class.model_name.human}"
= render :partial => "form"

app/views/groups/index.html.haml
- model_class = Group
%h1=t '.title', :default => model_class.model_name.human.pluralize
.row-fluid
  .well.well-small
    = simple_form_for @search, :url => groups_path, :method => :get, :html => { :class => "form-horizontal" } do |f|
      %legend Search for groups
      = f.input :name_or_description, label: 'Name or description contains:' 
      = f.submit "Search", :class => "btn btn-primary"
  - unless @groups.empty?
    = paginate @groups
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:description)
      %th Actions
  %tbody
    - @groups.each do |group|
      %tr
        %td= group.id
        %td= display_title group
        %td= group.description
        %td
          = link_to "Catalogs", catalog_path(group.root_catalog), class: 'btn'
          = link_to "Show", group_path(group), class: "btn"
          - if can_manage? group
            = link_to "Edit", edit_group_path(group), class: "btn"
            = link_to "Delete", group_path(group), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

app/views/groups/new.html.haml
- model_class = Group
.page-header
  %h1= "Create #{model_class.model_name.human}"
= render :partial => "form"

app/views/groups/show.html.haml
- provide(:title, 'Group')
- model_class = Group
%h1 Group

.row-fluid
  .span6
    %table.table
      %tbody
        %tr
          %th= model_class.human_attribute_name(:name) + ':'
          %td= @group.name
        %tr
          %th= model_class.human_attribute_name(:description) + ':'
          %td= @group.description
        %tr
          %th= model_class.human_attribute_name(:catalog_creation) + ':'
          %td= @group.catalog_creation
        %tr
          %th= model_class.human_attribute_name(:created_at) + ':'
          %td= @group.created_at
        %tr
          %th= model_class.human_attribute_name(:updated_at) + ':'
          %td= @group.updated_at
        %tr
          %th Assigned to projects:
          - if @group.projects.any?
            %td
              - @group.projects.each do |p|
                - if @group.shares_with_project?(p)
                  %i.icon-share
                = link_to p.name, project_path(p)
          - else
            %td No projects

    - if can_manage?(@group)
      = render "request_for_project"
      .form_actions
        = link_to "Edit group", edit_group_path(@group), class: 'btn'

  .span6
    - if can_manage? @group
      %div
        Users:
      - if @group.users.any?
        %ul
          - @group.users.each do |u|
            %li
              = "#{u.full_name} #{"(Owner)" if @group.created_by? u}"
              - unless @group.created_by? u
                = render partial: 'shared/permission_form', locals: { resource: @group, user: u }
      - else
        %td No users