config/routes.rb
DicomManager::Application.routes.draw do

	 resources :messages, :only => [:new, :create] do
     post 'act_admission_request', on: :member
	   collection do
       get 'admission_request'
       post 'send_admission_request'
	     get 'token' => 'messages#token', :as => 'token'
	     post 'empty/:messagebox' => 'messages#empty', :as => 'empty'
	     put 'update' => 'messages#update'
	     get ':messagebox/show/:id' => 'messages#show', :as => 'show', :constraints => { :messagebox => /inbox|outbox|trash/ }
	     get '(/:messagebox)' => 'messages#index', :as => 'box', :constraints => { :messagebox => /inbox|outbox|trash/ }
	   end
	 end


  devise_for :users, controllers: { registrations: "users/registrations" }

  namespace :admin do
    resources :users, constraints: { id: /[^\/]+/ }
    resources :groups, only: [:index]
    resources :projects, only: [:index]
    resources :catalogs, only: [:index]
  end

  namespace :user do
    resources :groups
    resources :projects
  end

  #resources
  resources :permissions
  resources :groups
  resources :projects
  resources :users do
    member do
      get 'edit_share'
      post 'update_share'
    end
  end
  resources :catalogs do
    post 'move', on: :member
    resources :dicom_files do
      post 'manage', on: :collection
      get 'view', on: :member
    end
  end


  #paths
  root :to => "static_pages#home"

  match '/help', to: "static_pages#help"

  match '/about', to: "static_pages#about"
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id          :integer(4)      not null, primary key
#  name        :string(255)
#  description :string(255)
#  created_at  :datetime        not null
#  updated_at  :datetime        not null
#  creator_id  :integer(4)
#  updater_id  :integer(4)
#

class Project < ActiveRecord::Base
  include CatalogExtension

  has_many :groups_projects, dependent: :destroy
  has_many :groups, through: :groups_projects
  has_many :catalogs, as: :catalogable
  belongs_to :author, class_name: 'User', foreign_key: 'creator_id', validate: true
  has_many :permissions, as: :permissionable
  has_one :root_catalog, class_name: "Catalog", as: :catalogable, conditions: { ancestry: nil }

  attr_accessible :name, :description, :group_ids, :catalog_creation, :creator_id, :updater_id

  after_create :create_root_catalog

  def created_by?(user)
    self.creator_id == user.id
  end

  def create_root_catalog
    catalog_description = "Root catalog for #{name} (#{self.class.to_s})"
    catalogs.create(name: name.downcase, description: catalog_description)
  end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < ApplicationController
  def index
    @search = Project.search params[:q]
    @projects = @search.result.page params[:page]
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :find_project, except: [:index, :create, :new]

  def index
    @search = current_user.projects.search params[:q]
    @projects = @search.result.page params[:page]
  end

  def show
  end

  def edit
    @available_groups = (@project.groups + current_user.created_groups).uniq
  end

  def new
    @project = Project.new
  end

  def create
    project = Project.new params[:project]

    if project.save
      flash[:success] = "Project created"
    else
      flash[:failure] = "Failed to create project"
    end
    redirect_to project_path(project)
  end

  def update
    if @project.update_attributes params[:project]
      flash[:success] = "Project updated"
      redirect_to project_path(@project)
    else
      flash[:error] = "Error updating project"
      render :edit
    end
  end

  def destroy
    if @project.destroy
      flash[:success] = "Project destroyed"
    else
      flash[:error] = "Could not destroy the project"
    end
    redirect_to project_path(@project)
  end

  private
  def find_project
    @project = Project.find params[:id]
  end
end

app/controllers/user/projects_controller.rb
class User::ProjectsController < ApplicationController
  def index
    @search = current_user.created_projects.search params[:q]
    @projects = @search.result.page params[:page]
  end
end

app/views/projects/_form.html.haml
.container-fluid
  = simple_form_for @project, :html => { :class => 'form-horizontal' } do |f|
    .row-fluid
      .span6
        = f.input :name
        = f.input :description
        = f.input :catalog_creation, wrapper_html: { class: 'checkbox' }
        = f.button :submit, :class => 'btn-primary'
      - unless @project.new_record?
        .span6
          = f.association :groups, collection: @available_groups, as: :check_boxes, label: "Assigned groups:", wrapper_html: { class: 'my-checkboxes' }

app/views/projects/edit.html.haml
- model_class = Project
.page-header
  %h1= "Edit #{model_class.model_name.human}"
= render :partial => "form"

app/views/projects/index.html.haml
- model_class = Project
%h1=t '.title', :default => model_class.model_name.human.pluralize
.row-fluid
  .well.well-small
    = simple_form_for @search, :url => admin_projects_path, :method => :get, :html => { :class => "form-horizontal" } do |f|
      %legend Search for projects
      = f.input :name_or_description, label: 'Name or description contains:' 
      = f.submit "Search", :class => "btn btn-primary"
  - unless @projects.empty?
    = paginate @projects
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:description)
      %th= model_class.human_attribute_name(:created_at)
      %th= model_class.human_attribute_name(:updated_at)
  %tbody
    - @projects.each do |project|
      %tr
        %td= project.id
        %td= display_title project
        %td= project.description
        %td= project.created_at
        %td= project.updated_at
        %td
          = link_to "Catalogs", catalog_path(project.root_catalog), class: 'btn'
          = link_to "Show", project_path(project), class: "btn"
          - if can_manage? project
            = link_to "Edit", edit_project_path(project), class: "btn"
            = link_to "Delete", project_path(project), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

app/views/projects/new.html.haml
- model_class = Project
.page-header
  %h1= "Create #{model_class.model_name.human}"
= render :partial => "form"

app/views/projects/show.html.haml
- provide(:title, 'Project')
- model_class = Project
%h1 Project

.row-fluid
  %table.table
    %tbody
      %tr
        %th= model_class.human_attribute_name(:name) + ':'
        %td= @project.name
      %tr
        %th= model_class.human_attribute_name(:description) + ':'
        %td= @project.description
      %tr
        %th= model_class.human_attribute_name(:catalog_creation) + ':'
        %td= @project.catalog_creation
      %tr
        %th= model_class.human_attribute_name(:created_at) + ':'
        %td= @project.created_at
      %tr
        %th= model_class.human_attribute_name(:updated_at) + ':'
        %td= @project.updated_at
      %tr
        %th Assigned groups:
        %td
          - if @project.groups.any?
            - @project.groups.each do |g|
              = link_to g.name, group_path(g)
          - else
            No groups

- if can_manage?(@project)
  .form_actions
    = link_to "Edit project", edit_project_path(@project), class: 'btn'