config/routes.rb
DicomManager::Application.routes.draw do

	 resources :messages, :only => [:new, :create] do
     post 'act_admission_request', on: :member
	   collection do
       get 'admission_request'
       post 'send_admission_request'
	     get 'token' => 'messages#token', :as => 'token'
	     post 'empty/:messagebox' => 'messages#empty', :as => 'empty'
	     put 'update' => 'messages#update'
	     get ':messagebox/show/:id' => 'messages#show', :as => 'show', :constraints => { :messagebox => /inbox|outbox|trash/ }
	     get '(/:messagebox)' => 'messages#index', :as => 'box', :constraints => { :messagebox => /inbox|outbox|trash/ }
	   end
	 end


  devise_for :users, controllers: { registrations: "users/registrations" }

  namespace :admin do
    resources :users, constraints: { id: /[^\/]+/ }
    resources :groups, only: [:index]
    resources :projects, only: [:index]
    resources :catalogs, only: [:index]
  end

  namespace :user do
    resources :groups
    resources :projects
  end

  #resources
  resources :permissions
  resources :groups
  resources :projects
  resources :users do
    member do
      get 'edit_share'
      post 'update_share'
    end
  end
  resources :catalogs do
    post 'move', on: :member
    resources :dicom_files do
      post 'manage', on: :collection
      get 'view', on: :member
    end
  end


  #paths
  root :to => "static_pages#home"

  match '/help', to: "static_pages#help"

  match '/about', to: "static_pages#about"
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer(4)      not null, primary key
#  login                  :string(255)
#  name                   :string(255)
#  surname                :string(255)
#  admin                  :boolean(1)      default(FALSE)
#  enabled                :boolean(1)
#  email                  :string(255)     default(""), not null
#  encrypted_password     :string(255)     default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer(4)      default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#

class User < ActiveRecord::Base

  include HasMessages
  include CatalogExtension
  has_many :messages

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :authentication_keys => [:user_login]

  model_stamper

  easy_roles :roles
  ROLES = %w[project_manager group_manager deanonymizer]


  # Virtual attribute for sign with email or login
  attr_accessor :user_login, :password_confirmation, :current_password

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,
                  :login, :surname, :name, :user_login, :current_password, :admin, :enabled, :group_ids, :groups_users_attributes, :roles

  # Relationships
  has_many :created_catalogs, class_name: 'Catalog', foreign_key: 'creator_id'
  has_many :created_groups, class_name: 'Group', foreign_key: 'creator_id'
  has_many :created_projects, class_name: 'Project', foreign_key: 'creator_id'
  has_many :created_dicoms, class_name: 'DicomFile', foreign_key: 'creator_id'
  has_many :catalogs, as: :catalogable
  has_many :groups_users, dependent: :destroy
  has_many :groups, through: :groups_users
  has_many :projects, through: :groups, group: :project_id
  has_many :permissions
  has_one :root_catalog, class_name: "Catalog", as: :catalogable, conditions: { ancestry: nil }

  accepts_nested_attributes_for :groups_users

  # PreSave actions
  before_save { |user| user.email = email.downcase }

  after_create :create_root_catalog

  #validations
  validates :name, presence: true, length: { maximum: 50 }
  validates :surname, presence: true, length: { maximum: 50 }
  validates :login, presence: true, length: { maximum: 20 }, uniqueness: { case_sensitive: false }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false}
  validates :password, length: { minimum: 8 }, on: :create
  validates :password_confirmation, presence: true, on: :create

  public

  def root_catalog_id
    self.root_catalog.id
  end


  def list_roles
    self.roles.join(" ").humanize.titleize
  end

  def full_name
    self.name + " " + self.surname
  end

  def shares_with_group?(group)
    groups_users.where(group_id: group).first.share
  end

  def has_permission?(action, resource)
    ids = resource.class.to_s == "Group" ? resource.id : resource.groups.pluck("groups.id")
    permissions.where(action: action, permissionable_type: 'Group', permissionable_id: ids).limit(1).exists?
  end




  def send_message?(options)
    send_message(options)
    true
  rescue Exception => e
    false
  end

  def send_message(options)
    unless options[:recipients].nil?
      transaction do

        recipients = options[:recipients]
        options.delete(:recipients)

        options[:subject_id] = Message.sequence_subject_id if options[:subject_id].nil?

        recipients.each do |rec|
          # => create message copies
          options[:user_id] = self.id
          options[:sender_id] = self.id
          options[:recipient_id] = rec.id
          options[:copies] = true
          Message.create(options)
          # => create message
          options[:user_id] = rec.id
          options[:sender_id] = self.id
          options[:recipient_id] = rec.id
          options[:copies] = false
          options[:parent_id] = Message.next_parent_id(options[:parent_id]) unless options[:parent_id].nil?
          Message.create(options)
        end
      end
    else
      raise "Required recipients"
    end
  rescue Exception => e
    raise e
  end

  def inbox(options = {})
    options[:deleted] = false
    options[:copies] = false
    self.messages.where(options)
  end

  def outbox(options = {})
    options[:deleted] = false
    options[:copies] = true
    self.messages.where(options)
  end

  def trash(options = {})
    options[:deleted] = true
    self.messages.where(options)
  end

  def empty_messages(options = {})
    if options.empty? or options[:inbox] or options[:outbox]
      self.inbox.update_all(:deleted => true)
      self.outbox.update_all(:deleted => true)
    elsif options[:trash]
      self.trash.delete_all
    end
  end



  private
  # Overides devise method to allow authentication by users email or login
    def self.find_first_by_auth_conditions(warden_conditions)
      conditions = warden_conditions.dup
      if user_login = conditions.delete(:user_login)
        where(conditions).where(["lower(login) = :value OR lower(email) = :value", { :value => user_login.downcase }]).first
      else
        where(conditions).first
      end
    end

    def create_root_catalog
      catalog_description = "Root catalog for #{full_name} (#{self.class.to_s})"
      catalogs.create(name: full_name.downcase, description: catalog_description, creator_id: self.id, updater_id: self.id)
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_filter :find_user, except: [:index]
  before_filter :prepare_roles, only: [:create, :update]

  def index
    @search = User.search params[:q]
    @users = @search.result.page params[:page]
  end

  def show
  end

  def edit
  end

  def update
    if @user.update_attributes params[:user]
      flash[:notice] = "User updated"
      redirect_to admin_user_path(@user)
    else
      flash[:error] = "Error updating user"
      render :edit
    end
  end

  private
  def find_user
    @user = User.find params[:id]
  end

  def prepare_roles
    params[:user][:roles] -= [""]
  end
end

app/controllers/user/groups_controller.rb
class User::GroupsController < ApplicationController
  def index
    @search = current_user.created_groups.search params[:q]
    @groups = @search.result.page params[:page]
  end
end

app/controllers/user/projects_controller.rb
class User::ProjectsController < ApplicationController
  def index
    @search = current_user.created_projects.search params[:q]
    @projects = @search.result.page params[:page]
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController <  Devise::RegistrationsController
  layout 'application'

  def update
    self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)

    if params[:user][:password].present?
      result = resource.update_with_password(params[resource_name])
    else
      result = resource.update_without_password(params[resource_name])
    end
    
    if result
      if is_navigational_format?
        if resource.respond_to?(:pending_reconfirmation?) && resource.pending_reconfirmation?
          flash_key = :update_needs_confirmation
        end
        set_flash_message :notice, flash_key || :updated
      end
      sign_in resource_name, resource, :bypass => true
      respond_with resource, :location => after_update_path_for(resource)
    else
      clean_up_passwords resource
      respond_with resource
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_filter :correct_user , only: [:show, :edit, :update, :edit_share, :update_share]

  def show
    @user = User.find(params[:id])
  end

  def edit
  end

  def update
  end

  def edit_share
    @user = User.find(params[:id])
  end

  def update_share
    if @user.update_attributes(params[:user])
      flash[:success] = "Sharing updated."
    else
      flash[:error] = "Failed to update user sharing."
    end
    redirect_to @user
  end

  private
  def correct_user
    @user = User.find(params[:id])
    if current_user.admin?
      redirect_to root_path unless current_user?(@user)
    end
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def resource
    @resource = current_user
  end

  def resource_name
    :user
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def can_manage?(resource)
    current_user.admin? || resource.created_by?(current_user)
  end

  def check_permission
    has_permission = true
    unless current_user.admin?
      if current_catalog.catalogable_type == "User"
        if current_catalog == current_user.root_catalog
          has_permission = false
        end
      else
        has_permission = current_user.has_permission?('create', current_catalog.catalogable)
      end
    end
    has_permission
  end

  def can_create?(resource_name)
    unless current_user.admin?
      current_user.send("is_#{resource_name}_manager?".to_sym)
    else
      true
    end
  end
end

app/views/admin/users/_form.html.haml
.container-fluid
  = simple_form_for [:admin, @user], :html => { :class => 'form-horizontal' } do |f|
    .row-fluid
      .span6
        = f.input :name
        = f.input :surname
        = f.input :login
        = f.input :email
        = f.input :admin, wrapper_html: { class: 'checkbox' }
        = f.input :enabled, wrapper_html: { class: 'checkbox' }
        = f.input :roles, as: :check_boxes, collection: User::ROLES.collect{ |r| [r.humanize.titleize, r] }, checked: @user.roles, wrapper_html: { class: 'my-checkboxes' }
        = f.button :submit, :class => 'btn-primary'
      .span6
        = f.association :groups, as: :check_boxes, label: "Assigned to groups:", wrapper_html: { class: 'my-checkboxes' }

app/views/admin/users/edit.html.haml
- model_class = User
.page-header
  %h1= "Edit #{model_class.model_name.human}"
= render :partial => "form"

app/views/admin/users/index.html.haml
- model_class = User
%h1=t '.title', :default => model_class.model_name.human.pluralize
.row-fluid
  .well.well-small
    = simple_form_for @search, :url => admin_users_path, :method => :get, :html => { :class => "form-horizontal" } do |f|
      %legend Search for users
      = f.input :name_or_surname, label: 'First/Last name contains:' 
      = f.submit "Search", :class => "btn btn-primary"
  - unless @users.empty?
    = paginate @users
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:full_name)
      %th= model_class.human_attribute_name(:login)
      %th= model_class.human_attribute_name(:email)
      %th= model_class.human_attribute_name(:last_sign_in_at)
  %tbody
    - @users.each do |user|
      %tr
        %td= user.id
        %td= user.full_name
        %td= user.login
        %td= user.email
        %td= user.last_sign_in_at
        %td
          = link_to "Edit", edit_admin_user_path(user), class: "btn"
          = link_to "Show", admin_user_path(user), class: "btn"
          = link_to "Delete", admin_user_path(user), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

app/views/admin/users/show.html.haml
- provide(:title, 'Profile')
- model_class = User
%h1 Profile

.row-fluid
  %table.table
    %tbody
      %tr
        %th= model_class.human_attribute_name(:name) + ':'
        %td= @user.name
      %tr
        %th= model_class.human_attribute_name(:surname) + ':'
        %td= @user.surname
      %tr
        %th= model_class.human_attribute_name(:login) + ':'
        %td= @user.login
      %tr
        %th= model_class.human_attribute_name(:admin) + ':'
        %td= @user.admin
      %tr
        %th= model_class.human_attribute_name(:roles) + ':'
        %td= @user.list_roles
      %tr
        %th= model_class.human_attribute_name(:enabled) + ':'
        %td= @user.enabled
      %tr
        %th= model_class.human_attribute_name(:sign_in_count) + ':'
        %td= @user.sign_in_count
      %tr
        %th= model_class.human_attribute_name(:last_sign_in_at) + ':'
        %td= @user.last_sign_in_at
      %tr
        %th= model_class.human_attribute_name(:last_sign_in_ip) + ':'
        %td= @user.last_sign_in_ip
      %tr
        %th= model_class.human_attribute_name(:created_at) + ':'
        %td= @user.created_at
      %tr
        %th= model_class.human_attribute_name(:updated_at) + ':'
        %td= @user.updated_at
      %tr
        %th Assigned to groups:
        %td
          - if @user.groups.any?
            - @user.groups.each do |g|
              = link_to g.name, group_path(g)
              ,
          - else
            No groups
      %tr
        %th Assigned to projects:
        %td
          - if @user.projects.to_a.any?
            - @user.projects.each do |p|
              = link_to p.name, project_path(p)
              ,
          - else
            No projects

.form_actions
  = link_to "Edit user", edit_admin_user_path(@user), class: 'btn'